services:
  proyecto-ie:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    ports:
      - 4233:4200
    volumes:
      - ./:/app
    command: ["ng","serve", "--host", "0.0.0.0"]
